namespace OfficeVersionsCore.Models;

/// <summary>
/// Represents a blocked IP address entry
/// </summary>
public class BlockedIp
{
    /// <summary>IP address that is blocked</summary>
    public string IpAddress { get; set; } = string.Empty;

    /// <summary>Reason the IP was blocked</summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>When the IP was blocked (UTC)</summary>
    public DateTime BlockedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When the block expires (UTC); null = permanent</summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>Whether the block was set manually by an admin (vs. auto-blocked)</summary>
    public bool IsManual { get; set; }

    /// <summary>Number of suspicious requests that triggered the auto-block</summary>
    public int SuspiciousRequestCount { get; set; }

    /// <summary>Whether this block entry is still active</summary>
    public bool IsActive => ExpiresAt == null || ExpiresAt > DateTime.UtcNow;
}

/// <summary>
/// Represents a security event for a single request
/// </summary>
public class SecurityEvent
{
    /// <summary>IP address of the requester</summary>
    public string IpAddress { get; set; } = string.Empty;

    /// <summary>Requested path</summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>HTTP method</summary>
    public string Method { get; set; } = string.Empty;

    /// <summary>User-Agent header</summary>
    public string UserAgent { get; set; } = string.Empty;

    /// <summary>Type of threat detected</summary>
    public SecurityThreatType ThreatType { get; set; }

    /// <summary>When the event occurred (UTC)</summary>
    public DateTime OccurredAt { get; set; } = DateTime.UtcNow;

    /// <summary>Human-readable description of the threat</summary>
    public string Description { get; set; } = string.Empty;
}

/// <summary>
/// Type of security threat detected
/// </summary>
public enum SecurityThreatType
{
    SuspiciousPath,
    SuspiciousUserAgent,
    ExcessiveRequests,
    ManualBlock,
    SqlInjection,
    PathTraversal,
    RapidRequests,
    ScannerDetected,
    AuthFailure,
    HoneypotAccess
}

/// <summary>
/// Severity level of a security alert
/// </summary>
public enum AlertLevel
{
    Info,
    Warning,
    Critical
}

/// <summary>
/// A security alert generated by the periodic monitoring analysis
/// </summary>
public class SecurityAlert
{
    /// <summary>Severity level</summary>
    public AlertLevel Level { get; set; }

    /// <summary>Short alert title</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Detailed alert message</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>IP address related to the alert (if applicable)</summary>
    public string? IpAddress { get; set; }

    /// <summary>When the alert was raised (UTC)</summary>
    public DateTime OccurredAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Aggregated security metrics over the current analysis window
/// </summary>
public class SecurityMetrics
{
    /// <summary>Start of the analysis window</summary>
    public DateTime WindowStart { get; set; }

    /// <summary>Total requests in the analysis window</summary>
    public long TotalRequests { get; set; }

    /// <summary>Requests per minute (average over window)</summary>
    public double RequestsPerMinute { get; set; }

    /// <summary>Total 404 responses in the window</summary>
    public int Total404s { get; set; }

    /// <summary>Total 500 responses in the window</summary>
    public int Total500s { get; set; }

    /// <summary>Error rate percentage (4xx+5xx / total)</summary>
    public double ErrorRatePercentage { get; set; }

    /// <summary>Number of auth failures in the window</summary>
    public int TotalAuthFailures { get; set; }

    /// <summary>Number of suspicious events in the window</summary>
    public int SuspiciousEventCount { get; set; }

    /// <summary>Top IPs by request count (IP -> count)</summary>
    public IDictionary<string, int> TopIpsByRequestCount { get; set; } = new Dictionary<string, int>();
}

/// <summary>
/// Summary of the current security monitoring state
/// </summary>
public class SecurityStatus
{
    /// <summary>Total number of currently blocked IPs</summary>
    public int BlockedIpCount { get; set; }

    /// <summary>Total security events recorded since startup</summary>
    public int TotalEventsRecorded { get; set; }

    /// <summary>All currently active blocked IPs</summary>
    public IList<BlockedIp> BlockedIps { get; set; } = [];

    /// <summary>Recent security events (up to last 100)</summary>
    public IList<SecurityEvent> RecentEvents { get; set; } = [];

    /// <summary>Current aggregated metrics</summary>
    public SecurityMetrics? Metrics { get; set; }

    /// <summary>Recent alerts generated by the monitoring service</summary>
    public IList<SecurityAlert> RecentAlerts { get; set; } = [];
}
